version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - team-persia-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - team-persia-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: team_persia_reports
      POSTGRES_USER: persia_user
      POSTGRES_PASSWORD: persia_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - team-persia-network

volumes:
  postgres_data:

networks:
  team-persia-network:
    driver: bridge